artifacts_root: artifacts

# This component(Or Phase) will download and store the dataset in a folder.
# When the code runs then the whole data file will be stored in "artifacts" folder.
data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1J89WgvbvAKrbhXHV7JHMRAKC4-drWYAy/view?usp=sharing
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


# In this component we will download a model (e.g:-VGG16 , InceptionNet) ans save it with us.
# We will use transfer learning for it.Use only pretrained weights our custom (fully connected) layer.
prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5        #Downloading a NN architecture from Keras.io
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5 # NN with custom FC layer will be saved here.
  # base_model_updated will be used for training.



# This component will use the above saved model or NN for model training.
training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5 #Trained model will be saved here.